# Generated by Django 5.0.6 on 2025-01-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('isbn', models.CharField(max_length=13, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('publish_date', models.DateField(null=True)),
            ],
        ),
    ]
