# Generated by Django 5.1.1 on 2024-09-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30, null=True)),
                ('course_name', models.CharField(max_length=50, null=True)),
                ('course_duration', models.IntegerField(null=True)),
                ('seat', models.IntegerField(null=True)),
            ],
        ),
    ]
