# Generated by Django 5.0.6 on 2024-06-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiApp2', '0002_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=100, null=True)),
                ('head', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
